# Generated by Django 5.1.1 on 2024-09-19 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsServices', '0001_initial'),
        ('usersPerson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='client_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersPerson.clienttenant'),
        ),
        migrations.AddField(
            model_name='marca',
            name='client_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersPerson.clienttenant'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsServices.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='client_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersPerson.clienttenant'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsServices.marca'),
        ),
        migrations.AddField(
            model_name='servico',
            name='client_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersPerson.clienttenant'),
        ),
    ]
